### PR TITLE
feat: Add offline support

### PR DESCRIPTION
**Pull request by mcmah309**
closes: https://github.com/Anush008/fastembed-rs/issues/88

### CODE REVIEW

**Comment by mcmah309** [comment]
Test failed due to recent jinaai model feature being merged. Should be good to run again.

**Review by Anush008 — APPROVED** [review]
Thanks again @mcmah309 🙏

**Comment by mcmah309** [comment]
Sorry cleaned up the git graph a bit. Now good :+1: No problem!

**Comment by mcmah309** [comment]
Workflow failed, but not seeing any stages that actually failed, looks like they all succeeded? :thinking:

**Comment by Anush008** [comment]
I've seen the cache action failure before. Shouldn't be a problem.

**Pull request merged**
