### PR TITLE
feat: add Alibaba-NLP/gte-base-en-v1.5

### PR DESCRIPTION
**Pull request by spikecodes**
This PR adds Alibaba's new gte-base-en-v1.5, along with test code for this model.

### CODE REVIEW

**Comment by Anush008** [comment]
We do have dimensionality tests that run for each model. So separate tests for this model won't be necessary.

https://github.com/Anush008/fastembed-rs/blob/main/src%2Ftests.rs#L12-L38

**Comment by spikecodes** [comment]
Sounds good, I've removed the tests for this model.

**Comment by Anush008** [comment]
Please run FMT and Clippy.

**Comment by spikecodes** [comment]
Sure, just did.

**Comment by Anush008** [comment]
Thank you 🙏

**Review by Anush008 — APPROVED** [review]

**Pull request merged**
