### PR TITLE
Update ort to 2.0.0-rc.8 to fix build issues

### PR DESCRIPTION
**Pull request by jawj**
See static linking fixes here: https://github.com/pykeio/ort/releases

### CODE REVIEW

**Comment by jawj** [comment]
Huh. https://github.com/pykeio/ort/issues/305

**Comment by dancixx** [comment]
Can you please merge this?

**Comment by Anush008** [comment]
Hey @dancixx.
I would've with a green CI. Until it's there, you can use the fork as the dependency in your project.

**Comment by Anush008** [comment]
Resolved with #124 
Thank you @jawj.

**Pull request closed without merging**
