### PR TITLE
feat: User defined reranking

### PR DESCRIPTION
**Pull request by jawj**
As previously discussed in #75, these changes allow a user-defined reranking model, similar to user-defined embedding models.

## Summary by CodeRabbit

- **New Features**
  - Introduced support for user-defined models in text embedding and reranking.
  - Added new struct `UserDefinedRerankingModel` for custom reranking models.
  - Added `local_model!` macro to define and load user-defined models.

- **Documentation**
  - Updated README to demonstrate how to load user-defined `.onnx` files for embedding and reranking models.

- **Chores**
  - Added George MacKerron as an author in the `Cargo.toml` file.

### CODE REVIEW

**Comment by jawj** [comment]
@Anush008 I'm not clear why GitHub thinks there's a conflict here: the start of the incoming change is identical to the existing code that it claims conflicts.

Please take a look and then perhaps you can resolve this in favour of the incoming code?

**Review by Anush008 — APPROVED** [review]
Looks good. Thanks @jawj.
Do you want to add a reference about user-defined reranking models in the README?

**Comment by Anush008** [comment]
Also, please feel free to add yourself to the authors list in the `Cargo.toml` file.

**Comment by Anush008** [comment]
I just realised, the README example looks a little terrifying but also cool. LOL 😆

**Pull request merged**
